name: NVSHMEM question
description: Ask the NVSHMEM team a question
title: "[Question]: "
labels: ["question"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reaching out! To solve your problem, feel free to check out the [user guide](https://docs.nvidia.com/nvshmem/api/using.html), in particular the FAQ section, and the [release notes](https://docs.nvidia.com/nvshmem/release-notes-install-guide/release-notes/index.html).
        ---
  - type: textarea
    id: question
    attributes:
      label: Question