# Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

include("${CMAKE_CURRENT_LIST_DIR}/NVSHMEMVersionStage.cmake")

# Version variables produced by this file:
#
#   NVSHMEM_BASE_VERSION:              public source/API version, e.g. MAJOR.MINOR.PATCH
#   NVSHMEM_NUMERIC_VERSION:           CMake project version, e.g. MAJOR.MINOR.PATCH.0
#   NVSHMEM_VERSION_STAGE:             artifact stage: dev, rc, or release
#   NVSHMEM_VERSION_STAGE_NUMBER:      non-negative dev/rc suffix number, e.g. N
#   NVSHMEM_ARTIFACT_VERSION:          package/upload version, e.g. MAJOR.MINOR.PATCH.devN,
#                                      MAJOR.MINOR.PATCHrcN, or MAJOR.MINOR.PATCH
#   NVSHMEM_PACKAGE_VERSION:           distro upstream version, e.g. MAJOR.MINOR.PATCH~rcN
#   NVSHMEM_PACKAGE_RELEASE:           distro package release, currently 0
#   NVSHMEM_DEBIAN_PACKAGE_VERSION:    full Debian version, e.g. MAJOR.MINOR.PATCH~rcN-0
#   NVSHMEM_RPM_PACKAGE_VERSION:       RPM Version field, e.g. MAJOR.MINOR.PATCH
#   NVSHMEM_RPM_PACKAGE_RELEASE:       RPM Release field, e.g. 0~rcN
#   NVSHMEM_VERSION_IS_PRERELEASE:     true for dev/rc artifacts; false for release

# Keep PROJECT_VERSION_TWEAK numeric and fixed so CMake, ABI checks, and existing package
# consumers continue to see MAJOR.MINOR.PATCH.0. Non-final artifact identity is represented
# by NVSHMEM_VERSION_STAGE and NVSHMEM_VERSION_STAGE_NUMBER instead.
if(NOT DEFINED PROJECT_VERSION_TWEAK OR NOT PROJECT_VERSION_TWEAK STREQUAL "0")
  message(FATAL_ERROR
          "NVSHMEM PROJECT_VERSION_TWEAK is frozen at 0. "
          "Use NVSHMEM_VERSION_STAGE environment values or "
          "NVSHMEM_VERSION_STAGE_OVERRIDE CMake values to distinguish "
          "development and release-candidate artifacts.")
endif()

set(NVSHMEM_VERSION_STAGE_OVERRIDE "" CACHE STRING
    "Explicit NVSHMEM artifact version stage override: dev, rc, release, or empty")
set_property(CACHE NVSHMEM_VERSION_STAGE_OVERRIDE PROPERTY STRINGS "" dev rc release)
set(NVSHMEM_VERSION_STAGE_NUMBER_OVERRIDE "" CACHE STRING
    "Explicit NVSHMEM artifact version stage number override, or empty")

# Resolve the stage type from branch defaults, then environment and CMake overrides.
set(NVSHMEM_VERSION_STAGE "${NVSHMEM_VERSION_STAGE_DEFAULT}")
set(NVSHMEM_VERSION_STAGE_NUMBER "${NVSHMEM_VERSION_STAGE_NUMBER_DEFAULT}")
set(_NVSHMEM_DEFAULT_VERSION_STAGE "${NVSHMEM_VERSION_STAGE_DEFAULT}")
string(STRIP "${_NVSHMEM_DEFAULT_VERSION_STAGE}" _NVSHMEM_DEFAULT_VERSION_STAGE)
string(TOLOWER "${_NVSHMEM_DEFAULT_VERSION_STAGE}" _NVSHMEM_DEFAULT_VERSION_STAGE)

set(_NVSHMEM_STAGE_EXPLICIT OFF)
set(_NVSHMEM_STAGE_NUMBER_EXPLICIT OFF)

if(DEFINED ENV{NVSHMEM_VERSION_STAGE})
  set(_NVSHMEM_ENV_STAGE "$ENV{NVSHMEM_VERSION_STAGE}")
  string(STRIP "${_NVSHMEM_ENV_STAGE}" _NVSHMEM_ENV_STAGE)
  if(NOT "${_NVSHMEM_ENV_STAGE}" STREQUAL "")
    set(NVSHMEM_VERSION_STAGE "${_NVSHMEM_ENV_STAGE}")
    set(_NVSHMEM_STAGE_EXPLICIT ON)
  endif()
endif()

if(DEFINED ENV{NVSHMEM_VERSION_STAGE_NUMBER})
  set(_NVSHMEM_ENV_STAGE_NUMBER "$ENV{NVSHMEM_VERSION_STAGE_NUMBER}")
  string(STRIP "${_NVSHMEM_ENV_STAGE_NUMBER}" _NVSHMEM_ENV_STAGE_NUMBER)
  if(NOT "${_NVSHMEM_ENV_STAGE_NUMBER}" STREQUAL "")
    set(NVSHMEM_VERSION_STAGE_NUMBER "${_NVSHMEM_ENV_STAGE_NUMBER}")
    set(_NVSHMEM_STAGE_NUMBER_EXPLICIT ON)
  endif()
endif()

set(_NVSHMEM_STAGE_OVERRIDE "${NVSHMEM_VERSION_STAGE_OVERRIDE}")
string(STRIP "${_NVSHMEM_STAGE_OVERRIDE}" _NVSHMEM_STAGE_OVERRIDE)
if(NOT "${_NVSHMEM_STAGE_OVERRIDE}" STREQUAL "")
  set(NVSHMEM_VERSION_STAGE "${_NVSHMEM_STAGE_OVERRIDE}")
  set(_NVSHMEM_STAGE_EXPLICIT ON)
endif()

set(_NVSHMEM_STAGE_NUMBER_OVERRIDE "${NVSHMEM_VERSION_STAGE_NUMBER_OVERRIDE}")
string(STRIP "${_NVSHMEM_STAGE_NUMBER_OVERRIDE}" _NVSHMEM_STAGE_NUMBER_OVERRIDE)
if(NOT "${_NVSHMEM_STAGE_NUMBER_OVERRIDE}" STREQUAL "")
  set(NVSHMEM_VERSION_STAGE_NUMBER "${_NVSHMEM_STAGE_NUMBER_OVERRIDE}")
  set(_NVSHMEM_STAGE_NUMBER_EXPLICIT ON)
endif()

# Normalize the selected stage
string(STRIP "${NVSHMEM_VERSION_STAGE}" NVSHMEM_VERSION_STAGE)
string(TOLOWER "${NVSHMEM_VERSION_STAGE}" NVSHMEM_VERSION_STAGE)
string(STRIP "${NVSHMEM_VERSION_STAGE_NUMBER}" NVSHMEM_VERSION_STAGE_NUMBER)

# If only the stage type is changed, clear the branch default stage number.
if(_NVSHMEM_STAGE_EXPLICIT AND
   NOT _NVSHMEM_STAGE_NUMBER_EXPLICIT AND
   NOT "${NVSHMEM_VERSION_STAGE}" STREQUAL "${_NVSHMEM_DEFAULT_VERSION_STAGE}")
  set(NVSHMEM_VERSION_STAGE_NUMBER "")
endif()

# Split the CMake version from the artifact version
set(NVSHMEM_BASE_VERSION
    "${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH}"
    CACHE STRING "NVSHMEM base public version" FORCE)
set(NVSHMEM_NUMERIC_VERSION "${PROJECT_VERSION}"
    CACHE STRING "NVSHMEM numeric CMake project version" FORCE)

# Final releases are unsuffixed with an empty or 0 stage value
if(NVSHMEM_VERSION_STAGE STREQUAL "release")
  if(NOT NVSHMEM_VERSION_STAGE_NUMBER STREQUAL "" AND
     NOT NVSHMEM_VERSION_STAGE_NUMBER STREQUAL "0")
    message(FATAL_ERROR "NVSHMEM_VERSION_STAGE_NUMBER must be empty or 0 for release builds")
  endif()
  set(NVSHMEM_VERSION_STAGE_NUMBER "")
  set(NVSHMEM_ARTIFACT_VERSION "${NVSHMEM_BASE_VERSION}")
  set(NVSHMEM_PACKAGE_VERSION "${NVSHMEM_BASE_VERSION}")
# RC artifacts use PEP 440-compatible suffixes and distro versions that sort before final releases.
elseif(NVSHMEM_VERSION_STAGE STREQUAL "rc")
  if(NOT NVSHMEM_VERSION_STAGE_NUMBER MATCHES "^[0-9]+$")
    message(FATAL_ERROR "NVSHMEM_VERSION_STAGE_NUMBER must be a non-negative integer for rc builds")
  endif()
  set(NVSHMEM_ARTIFACT_VERSION "${NVSHMEM_BASE_VERSION}rc${NVSHMEM_VERSION_STAGE_NUMBER}")
  set(NVSHMEM_PACKAGE_VERSION "${NVSHMEM_BASE_VERSION}~rc${NVSHMEM_VERSION_STAGE_NUMBER}")
# Development artifacts are derived from external CI state, otherwise defaulting to 0.
elseif(NVSHMEM_VERSION_STAGE STREQUAL "dev")
  if(NVSHMEM_VERSION_STAGE_NUMBER STREQUAL "")
    if(DEFINED ENV{DVS_SW_CHANGELIST})
      set(NVSHMEM_VERSION_STAGE_NUMBER "$ENV{DVS_SW_CHANGELIST}")
    elseif(DEFINED ENV{CI_PIPELINE_IID})
      set(NVSHMEM_VERSION_STAGE_NUMBER "$ENV{CI_PIPELINE_IID}")
    elseif(DEFINED ENV{CI_PIPELINE_ID})
      set(NVSHMEM_VERSION_STAGE_NUMBER "$ENV{CI_PIPELINE_ID}")
    else()
      set(NVSHMEM_VERSION_STAGE_NUMBER "0")
    endif()
  endif()
  if(NOT NVSHMEM_VERSION_STAGE_NUMBER MATCHES "^[0-9]+$")
    message(FATAL_ERROR "NVSHMEM_VERSION_STAGE_NUMBER must be a non-negative integer for dev builds")
  endif()
  set(NVSHMEM_ARTIFACT_VERSION "${NVSHMEM_BASE_VERSION}.dev${NVSHMEM_VERSION_STAGE_NUMBER}")
  set(NVSHMEM_PACKAGE_VERSION "${NVSHMEM_BASE_VERSION}~dev${NVSHMEM_VERSION_STAGE_NUMBER}")
else()
  message(FATAL_ERROR "NVSHMEM_VERSION_STAGE must be one of: dev, rc, release")
endif()

# Appropriately map artifact identity to Debian and RPM package formatting
set(NVSHMEM_PACKAGE_RELEASE "0")
set(NVSHMEM_DEBIAN_PACKAGE_VERSION "${NVSHMEM_PACKAGE_VERSION}-${NVSHMEM_PACKAGE_RELEASE}")
set(NVSHMEM_RPM_PACKAGE_VERSION "${NVSHMEM_BASE_VERSION}")
if(NVSHMEM_VERSION_STAGE STREQUAL "release")
  set(NVSHMEM_RPM_PACKAGE_RELEASE "${NVSHMEM_PACKAGE_RELEASE}")
elseif(NVSHMEM_VERSION_STAGE STREQUAL "rc")
  set(NVSHMEM_RPM_PACKAGE_RELEASE "0~rc${NVSHMEM_VERSION_STAGE_NUMBER}")
else()
  set(NVSHMEM_RPM_PACKAGE_RELEASE "0~dev${NVSHMEM_VERSION_STAGE_NUMBER}")
endif()

# Identify release vs pre-release
if(NVSHMEM_VERSION_STAGE STREQUAL "release")
  set(NVSHMEM_VERSION_IS_PRERELEASE OFF)
else()
  set(NVSHMEM_VERSION_IS_PRERELEASE ON)
endif()

# Export final values
set(NVSHMEM_VERSION_STAGE "${NVSHMEM_VERSION_STAGE}" CACHE STRING
    "NVSHMEM artifact version stage: dev, rc, or release" FORCE)
set(NVSHMEM_VERSION_STAGE_NUMBER "${NVSHMEM_VERSION_STAGE_NUMBER}" CACHE STRING
    "NVSHMEM artifact version stage number" FORCE)
set(NVSHMEM_ARTIFACT_VERSION "${NVSHMEM_ARTIFACT_VERSION}" CACHE STRING
    "NVSHMEM publishable artifact version" FORCE)
set(NVSHMEM_PACKAGE_VERSION "${NVSHMEM_PACKAGE_VERSION}" CACHE STRING
    "NVSHMEM distro package upstream version" FORCE)
set(NVSHMEM_PACKAGE_RELEASE "${NVSHMEM_PACKAGE_RELEASE}" CACHE STRING
    "NVSHMEM distro package release" FORCE)
set(NVSHMEM_DEBIAN_PACKAGE_VERSION "${NVSHMEM_DEBIAN_PACKAGE_VERSION}" CACHE STRING
    "NVSHMEM Debian package version" FORCE)
set(NVSHMEM_RPM_PACKAGE_VERSION "${NVSHMEM_RPM_PACKAGE_VERSION}" CACHE STRING
    "NVSHMEM RPM package version" FORCE)
set(NVSHMEM_RPM_PACKAGE_RELEASE "${NVSHMEM_RPM_PACKAGE_RELEASE}" CACHE STRING
    "NVSHMEM RPM package release" FORCE)
set(NVSHMEM_VERSION_IS_PRERELEASE "${NVSHMEM_VERSION_IS_PRERELEASE}" CACHE BOOL
    "Whether the NVSHMEM artifact version is a pre-release" FORCE)

message(STATUS "NVSHMEM_ARTIFACT_VERSION: ${NVSHMEM_ARTIFACT_VERSION}")
